Fix possible bug due to sprintf() overwrite
Fixed compiler error:
error: ‘sprintf’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]

Signed-off-by: Ilan Smith <ilansm@nvidia.com>